# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_strings"
version = "2.0.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "string manipulation"
categories = ["strings"]
keywords = ["fortran", "strings"]
homepage = "https://github.com/urbanjost/M_strings.git"

# demo programs
[install]
library="true"

[[test]]
name="test_suite"
source-dir="test"
main="test_suite_M_strings.f90"
[test.dependencies]
M_msg          = { git = "https://github.com/urbanjost/M_msg.git" }
