# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_strings"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "string manipulation (STD:2008)"
# demo programs

executable = [
{  name="demo_adjustc",           source-dir="example",  main="adjustc.f90"           },
{  name="demo_atleast",           source-dir="example",  main="atleast.f90"           },
{  name="demo_base",              source-dir="example",  main="base.f90"              },
#{  name="demo_c2s",               source-dir="example",  main="c2s.f90"               },
{  name="demo_change",            source-dir="example",  main="change.f90"            },
{  name="demo_chomp",             source-dir="example",  main="chomp.f90"             },
{  name="demo_codebase",          source-dir="example",  main="codebase.f90"          },
{  name="demo_compact",           source-dir="example",  main="compact.f90"           },
{  name="demo_crop",              source-dir="example",  main="crop.f90"              },
{  name="demo_decodebase",        source-dir="example",  main="decodebase.f90"        },
{  name="demo_delim",             source-dir="example",  main="delim.f90"             },
{  name="demo_describe",          source-dir="example",  main="describe.f90"          },
{  name="demo_expand",            source-dir="example",  main="expand.f90"            },
{  name="demo_fmt",               source-dir="example",  main="fmt.f90"               },
{  name="demo_fortran_name",      source-dir="example",  main="fortran_name.f90"      },
{  name="demo_getvals",           source-dir="example",  main="getvals.f90"           },
{  name="demo_indent",            source-dir="example",  main="indent.f90"            },
{  name="demo_isalnum",           source-dir="example",  main="isalnum.f90"           },
{  name="demo_isalpha",           source-dir="example",  main="isalpha.f90"           },
{  name="demo_isascii",           source-dir="example",  main="isascii.f90"           },
{  name="demo_isblank",           source-dir="example",  main="isblank.f90"           },
{  name="demo_iscntrl",           source-dir="example",  main="iscntrl.f90"           },
{  name="demo_isdigit",           source-dir="example",  main="isdigit.f90"           },
{  name="demo_isgraph",           source-dir="example",  main="isgraph.f90"           },
{  name="demo_islower",           source-dir="example",  main="islower.f90"           },
{  name="demo_isnumber",          source-dir="example",  main="isnumber.f90"          },
{  name="demo_isprint",           source-dir="example",  main="isprint.f90"           },
{  name="demo_ispunct",           source-dir="example",  main="ispunct.f90"           },
{  name="demo_isspace",           source-dir="example",  main="isspace.f90"           },
{  name="demo_isupper",           source-dir="example",  main="isupper.f90"           },
{  name="demo_isxdigit",          source-dir="example",  main="isxdigit.f90"          },
{  name="demo_join",              source-dir="example",  main="join.f90"              },
{  name="demo_lenset",            source-dir="example",  main="lenset.f90"            },
{  name="demo_len_white",         source-dir="example",  main="len_white.f90"         },
{  name="demo_listout",           source-dir="example",  main="listout.f90"           },
{  name="demo_lower",             source-dir="example",  main="lower.f90"             },
{  name="demo_matchw",            source-dir="example",  main="matchw.f90"            },
{  name="demo_merge_str",         source-dir="example",  main="merge_str.f90"         },
{  name="demo_modif",             source-dir="example",  main="modif.f90"             },
{  name="demo_msg",               source-dir="example",  main="msg.f90"               },
{  name="demo_M_strings",         source-dir="example",  main="M_strings.f90"         },
{  name="demo_M_strings_oop",     source-dir="example",  main="M_strings_oop.f90"     },
{  name="demo_noesc",             source-dir="example",  main="noesc.f90"             },
{  name="demo_nospace",           source-dir="example",  main="nospace.f90"           },
{  name="demo_notabs",            source-dir="example",  main="notabs.f90"            },
{  name="demo_quote",             source-dir="example",  main="quote.f90"             },
{  name="demo_replace",           source-dir="example",  main="replace.f90"           },
{  name="demo_reverse",           source-dir="example",  main="reverse.f90"           },
{  name="demo_rotate13",          source-dir="example",  main="rotate13.f90"          },
{  name="demo_s2c",               source-dir="example",  main="s2c.f90"               },
{  name="demo_s2v",               source-dir="example",  main="s2v.f90"               },
{  name="demo_s2vs",              source-dir="example",  main="s2vs.f90"              },
{  name="demo_sep",               source-dir="example",  main="sep.f90"               },
{  name="demo_split2020",         source-dir="example",  main="split2020.f90"         },
{  name="demo_split",             source-dir="example",  main="split.f90"             },
{  name="demo_stretch",           source-dir="example",  main="stretch.f90"           },
{  name="demo_string_to_value",   source-dir="example",  main="string_to_value.f90"   },
{  name="demo_string_to_values",  source-dir="example",  main="string_to_values.f90"  },
{  name="demo_strtok",            source-dir="example",  main="strtok.f90"            },
{  name="demo_substitute",        source-dir="example",  main="substitute.f90"        },
{  name="demo_switch",            source-dir="example",  main="switch.f90"            },
{  name="demo_transliterate",     source-dir="example",  main="transliterate.f90"     },
{  name="demo_unquote",           source-dir="example",  main="unquote.f90"           },
{  name="demo_upper",             source-dir="example",  main="upper.f90"             },
{  name="demo_upper_quoted",      source-dir="example",  main="upper_quoted.f90"      },
{  name="demo_v2s",               source-dir="example",  main="v2s.f90"               },
{  name="demo_value_to_string",   source-dir="example",  main="value_to_string.f90"   },
{  name="demo_visible",           source-dir="example",  main="visible.f90"           }
]

#auto-executables = false
#auto-tests = false

[[test]]
name="test_suite"
source-dir="test"
main="test_suite_M_strings.f90"
[test.dependencies]
M_msg          = { git = "https://github.com/urbanjost/M_msg.git" }
