m_journal Module Reference
Data Types
interface journal
interface str
Functions/Subroutines
character(len=:) function, allocatable msg_scalar (generic0, generic1, generic2, generic3, generic4, generic5, generic6, generic7, generic8, generic9, generica, genericb, genericc, genericd, generice, genericf, genericg, generich, generici, genericj, nospace)
character(len=:) function, allocatable msg_one (generic0, generic1, generic2, generic3, generic4, generic5, generic6, generic7, generic8, generic9, nospace)
subroutine where_write_message (where, msg)
subroutine flush_trail ()
subroutine set_stdout_lun (iounit)
subroutine where_write_message_all (where, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, nospace)
subroutine write_message_only (message)
Variables
integer, save, private stdout =OUTPUT_UNIT
logical, save debug =.false.
integer, save last_int =0
Function/Subroutine Documentation
flush_trail()
subroutine m_journal::flush_trail () [private]
References where_write_message().
msg_one()
character(len=:) function, allocatable m_journal::msg_one (class(*), dimension(:), intent(in) generic0, class(*), dimension(:), intent(in), optional generic1, class(*), dimension(:), intent(in), optional generic2, class(*), dimension(:), intent(in), optional generic3, class(*), dimension(:), intent(in), optional generic4, class(*), dimension(:), intent(in), optional generic5, class(*), dimension(:), intent(in), optional generic6, class(*), dimension(:), intent(in), optional generic7, class(*), dimension(:), intent(in), optional generic8, class(*), dimension(:), intent(in), optional generic9, logical, intent(in), optional nospace) [private]
References print_generic().
msg_scalar()
character(len=:) function, allocatable m_journal::msg_scalar (class(*), intent(in), optional generic0, class(*), intent(in), optional generic1, class(*), intent(in), optional generic2, class(*), intent(in), optional generic3, class(*), intent(in), optional generic4, class(*), intent(in), optional generic5, class(*), intent(in), optional generic6, class(*), intent(in), optional generic7, class(*), intent(in), optional generic8, class(*), intent(in), optional generic9, class(*), intent(in), optional generica, class(*), intent(in), optional genericb, class(*), intent(in), optional genericc, class(*), intent(in), optional genericd, class(*), intent(in), optional generice, class(*), intent(in), optional genericf, class(*), intent(in), optional genericg, class(*), intent(in), optional generich, class(*), intent(in), optional generici, class(*), intent(in), optional genericj, logical, intent(in), optional nospace) [private]
References print_generic().
set_stdout_lun()
subroutine m_journal::set_stdout_lun (integer, intent(in) iounit) [private]
References stdout.
where_write_message()
subroutine m_journal::where_write_message (character(len=*), intent(in) where, character(len=*), intent(in) msg) [private]
References debug, last_int, and stdout.
where_write_message_all()
subroutine m_journal::where_write_message_all (character(len=*), intent(in) where, class(*), intent(in) g0, class(*), intent(in), optional g1, class(*), intent(in), optional g2, class(*), intent(in), optional g3, class(*), intent(in), optional g4, class(*), intent(in), optional g5, class(*), intent(in), optional g6, class(*), intent(in), optional g7, class(*), intent(in), optional g8, class(*), intent(in), optional g9, logical, intent(in), optional nospace) [private]
References where_write_message().
write_message_only()
subroutine m_journal::write_message_only (character(len=*), intent(in) message) [private]
References where_write_message().
Variable Documentation
debug
logical, save m_journal::debug =.false. [private]
last_int
integer, save m_journal::last_int =0 [private]
stdout
integer, save, private m_journal::stdout =OUTPUT_UNIT [private]