m_strings_oop::string Interface Reference
Private Member Functions
procedure adjustc => oop_adjustc
procedure adjustl => oop_adjustl
procedure adjustr => oop_adjustr
procedure compact => oop_compact
procedure crop => oop_crop
procedure dble => oop_dble
procedure expand => oop_expand
procedure index => oop_index
procedure init => init_string
procedure int => oop_int
procedure len => oop_len
procedure len_trim => oop_len_trim
procedure lenset => oop_lenset
procedure atleast => oop_atleast
procedure match => oop_matchw
procedure lower => oop_lower
procedure noesc => oop_noesc
procedure notabs => oop_notabs
procedure real => oop_real
procedure reverse => oop_reverse
procedure substitute => oop_substitute
procedure transliterate => oop_transliterate
procedure trim => oop_trim
procedure upper => oop_upper
procedure chars => oop_switch
procedure, private eq
generic operator => eq
procedure, private lt
generic operator => lt
procedure, private gt
generic operator => gt
procedure, private ge
generic operator => ge
procedure, private le
generic operator => le
procedure, private ne
generic operator => ne
procedure, private string_plus_value
generic operator => string_plus_value
procedure, private string_minus_value
generic operator => string_minus_value
procedure, private string_multiply_value
generic operator => string_multiply_value
procedure, private string_append_value
generic operator => string_append_value
type(string) function construct_from_fill (chars, len)
Private Attributes
character(len=:), allocatable str
Member Function/Subroutine Documentation
adjustc()
procedure m_strings_oop::string::adjustc () [private]
adjustl()
procedure m_strings_oop::string::adjustl () [private]
adjustr()
procedure m_strings_oop::string::adjustr () [private]
atleast()
procedure m_strings_oop::string::atleast () [private]
chars()
procedure m_strings_oop::string::chars () [private]
compact()
procedure m_strings_oop::string::compact () [private]
construct_from_fill()
type(string) function m_strings_oop::string::construct_from_fill (character(len=*), intent(in), optional chars, integer, intent(in), optional len) [private]
crop()
procedure m_strings_oop::string::crop () [private]
dble()
procedure m_strings_oop::string::dble () [private]
eq()
procedure, private m_strings_oop::string::eq () [private]
expand()
procedure m_strings_oop::string::expand () [private]
ge()
procedure, private m_strings_oop::string::ge () [private]
gt()
procedure, private m_strings_oop::string::gt () [private]
index()
procedure m_strings_oop::string::index () [private]
init()
procedure m_strings_oop::string::init () [private]
int()
procedure m_strings_oop::string::int () [private]
le()
procedure, private m_strings_oop::string::le () [private]
len()
procedure m_strings_oop::string::len () [private]
len_trim()
procedure m_strings_oop::string::len_trim () [private]
lenset()
procedure m_strings_oop::string::lenset () [private]
lower()
procedure m_strings_oop::string::lower () [private]
lt()
procedure, private m_strings_oop::string::lt () [private]
match()
procedure m_strings_oop::string::match () [private]
ne()
procedure, private m_strings_oop::string::ne () [private]
noesc()
procedure m_strings_oop::string::noesc () [private]
notabs()
procedure m_strings_oop::string::notabs () [private]
operator() [1/10]
generic m_strings_oop::string::operator () [private]
References m_strings_oop::eq().
operator() [2/10]
generic m_strings_oop::string::operator () [private]
References m_strings_oop::lt().
operator() [3/10]
generic m_strings_oop::string::operator () [private]
References m_strings_oop::gt().
operator() [4/10]
generic m_strings_oop::string::operator () [private]
References m_strings_oop::ge().
operator() [5/10]
generic m_strings_oop::string::operator () [private]
References m_strings_oop::le().
operator() [6/10]
generic m_strings_oop::string::operator () [private]
References m_strings_oop::ne().
operator() [7/10]
generic m_strings_oop::string::operator () [private]
References m_strings_oop::string_plus_value().
operator() [8/10]
generic m_strings_oop::string::operator () [private]
References m_strings_oop::string_minus_value().
operator() [9/10]
generic m_strings_oop::string::operator () [private]
References m_strings_oop::string_multiply_value().
operator() [10/10]
generic m_strings_oop::string::operator () [private]
References m_strings_oop::construct_from_fill(), and m_strings_oop::string_append_value().
real()
procedure m_strings_oop::string::real () [private]
reverse()
procedure m_strings_oop::string::reverse () [private]
string_append_value()
procedure, private m_strings_oop::string::string_append_value () [private]
string_minus_value()
procedure, private m_strings_oop::string::string_minus_value () [private]
string_multiply_value()
procedure, private m_strings_oop::string::string_multiply_value () [private]
string_plus_value()
procedure, private m_strings_oop::string::string_plus_value () [private]
substitute()
procedure m_strings_oop::string::substitute () [private]
transliterate()
procedure m_strings_oop::string::transliterate () [private]
trim()
procedure m_strings_oop::string::trim () [private]
upper()
procedure m_strings_oop::string::upper () [private]
Member Data Documentation
str
character(len=:), allocatable m_strings_oop::string::str [private]
The documentation for this interface was generated from the following file:
/home/urbanjs/venus/V600/github/M_strings/src/M_strings_oop.f90