name: windows with gfortran

on: [push, pull_request]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        gcc_v: [11] # Version of GFortran we want to use.
        include:

        - os: windows-latest
          os-arch: windows-x86_64
          release-flags: --flag '--static -g -fbacktrace -O3'
          exe: .exe

    env:
      FC: gfortran
      GCC_V: ${{ matrix.gcc_v }}
      TZ: UTC+04:00

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install fpm
      run: |
           Set-PSDebug -Trace 1
           $Env:Path += [IO.Path]::PathSeparator + $pwd
           curl https://raw.githubusercontent.com/urbanjost/index/main/bootstrap/fpm.F90 --output fpm.F90
           gfortran -D_WIN32 fpm.F90 -g -fbacktrace -o fpm.exe
           ls fpm.exe
           curl https://raw.githubusercontent.com/urbanjost/index/main/bootstrap/hello.f90 --output hello.f90
           gfortran hello.f90 -g -fbacktrace -o hello.exe
           ls hello.exe
    - name: Display environment
      run: |
        Set-PSDebug -Trace 1
        $Env:Path += [IO.Path]::PathSeparator + $pwd
        make -k -p -fNOTTHERE
        pwd
        uname -a
        echo "end" > foo.f90
        gfortran -cpp -E -dM foo.f90
        env
        which gfortran
        gfortran --version
        hello.exe
        hello
        fpm --version
        exit 0

    - name: tests MSWindows (debug)
      run: |
           Set-PSDebug -Trace 1
           $Env:Path += [IO.Path]::PathSeparator + $pwd
           fpm.exe test --profile debug -flag "-D _WIN32"

    - name: tests MSWindows (release)
      run: |
           Set-PSDebug -Trace 1
           $Env:Path += [IO.Path]::PathSeparator + $pwd
           fpm.exe test --profile release -flag "-D _WIN32"

#    - name: Run demo programs (fpm run)
#      run: fpm run --profile release

    - name: cleanup MSWindows
      run: dir
